# Arithmetic operations on NumPy Array

In [1]:
import numpy as np

### Arithmetic Operations - add(), subtraction(), multiply(), division(), power(), mod()

In [2]:
arr_1 = np.array([2,6,3,9])
final_arr = arr_1 + 2        #We can add scaler value to all elements of an array.
print(final_arr)

[ 4  8  5 11]


In [3]:
arr_1 = np.array([2,6,3,9])
arr_2 = np.array([8,2,5,1])

final_arr = arr_1 + arr_2
print(final_arr)

[10  8  8 10]


In [4]:
final_arr = np.add(arr_1, arr_2)
print(final_arr)

[10  8  8 10]


In [5]:
arr_1 = np.array([[2,6,3,9], [8,2,5,1]])
arr_2 = np.array([[9,2,5,3], [8,2,5,1]])
arr_3 = np.array([[1,2,3,4], [1,2,3,4]])

final_arr = arr_1 + arr_2 + arr_3
print(final_arr)

[[12 10 11 16]
 [17  6 13  6]]


In [6]:
final_arr = np.add(arr_1, arr_2, arr_3) #Third array(Arr_3) is not added.
final_arr

array([[11,  8,  8, 12],
       [16,  4, 10,  2]])

### power()

In [7]:
arr_1 = np.array([2,6,3,9])
final_arr = arr_1 ** 2       # We can use np.power(arr_1, 2) for the same purose.
final_arr

array([ 4, 36,  9, 81])

### mod()

In [8]:
arr_1 = np.array([2,6,3,9])
final_arr = arr_1 % 2       # We can use np.mod(arr_1, 2) for the same purose.
final_arr

array([0, 0, 1, 1], dtype=int32)

### Multiplication of 2D arrays

In [9]:
arr_1 = np.array([[2,6,3,9], [8,2,5,1]])
arr_2 = np.array([[9,2,5,3], [8,2,5,1]])

final_arr = arr_1 * arr_2
print(final_arr)

[[18 12 15 27]
 [64  4 25  1]]


### reciprocal()

In [10]:
arr_2 = np.array([[9,2,5,3], [8,2,5,1]], dtype='f')
final_arr = np.reciprocal(arr_2)
print(final_arr)

[[0.11111111 0.5        0.2        0.33333334]
 [0.125      0.5        0.2        1.        ]]


### Broadcasting - Ability to perform arithmetic operations on arrays of different shapes

In [11]:
one_arr = np.array([2,4,6])
another_arr = np.array([1,2])
final_arr = one_arr + another_arr
print(final_arr)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [12]:
one_arr = np.array([2,4,6])
another_arr = np.array([2])
final_arr = one_arr + another_arr     # numpy converts 2 to [2,2,2] - smaller array Broadcasting to match larger array    
print(final_arr)

[4 6 8]


# Statistical Operations on NumPy Arrays

### Column-wise mean()

In [13]:
example_arr = np.array([[9,2,5,3], [8,2,5,2]], dtype='f')

result = np.mean(example_arr, axis=1)
print(result)

[4.75 4.25]


### Row-wise std()

In [14]:
example_arr = np.array([[9,2,5,3], [8,2,5,2]], dtype='f')

result = np.std(example_arr, axis=0)
print(result)

[0.5 0.  0.  0.5]
