# Frequently used functions of numpy array

In [ ]:
import numpy as np

In [ ]:
array = np.array([2,4,5,1,4,2,4,9,7])

array

### Fetching unique elements

In [ ]:
unique_arr = np.unique(array)

print(unique_arr)

### Sorting an array

In [5]:
sorted_arr = np.sort(array)

print(sorted_arr)

[1 2 2 4 4 4 5 7 9]


### Shuffling content of an array

In [8]:
np.random.shuffle(sorted_arr)

print(sorted_arr)

[7 9 2 2 5 1 4 4 4]


### Reshaping an array

In [9]:
print(array)

[2 4 5 1 4 2 4 9 7]


In [10]:
new_arr = np.resize(array,(3,3))

print(new_arr)

[[2 4 5]
 [1 4 2]
 [4 9 7]]


In [11]:
flattened_arr = np.ravel(new_arr)

print(flattened_arr)

[2 4 5 1 4 2 4 9 7]


### Searching element(s) from array

#### Linear Search

In [12]:
np.where(flattened_arr == 4)

(array([1, 4, 6], dtype=int64),)

In [13]:
np.where(flattened_arr % 2 == 0)

(array([0, 1, 4, 5, 6], dtype=int64),)

#### Binary Search - works only on sorted array

In [14]:
sorted_arr = np.array([2,4,6,8,10])

np.searchsorted(sorted_arr, 8)

3

### Filter an array

In [15]:
fc = [True, False, False, True, True]

filtered_arr = sorted_arr[fc]

print(filtered_arr)

[ 2  8 10]


In [16]:
fc = sorted_arr % 4 == 0

filtered_arr = sorted_arr[fc]

print(filtered_arr)

[4 8]
