# N-Dimensional Arrays in NumPy

In [2]:
pip install numpy 

In [3]:
import numpy as np # import numpy to use it's functions/methods 

### Option 1: Creating arrays using python lists/tuples

In [4]:
array = np.array([2,5,7,9], dtype='int32') 

array

array([2, 5, 7, 9])

In [5]:
array.dtype

dtype('int32')

In [6]:
array.shape

(4,)

In [7]:
array.ndim

1

In [8]:
array_2d = np.array([[2,5,7,9],[1,3,4,10]], dtype='int32') 
array_2d

array([[ 2,  5,  7,  9],
       [ 1,  3,  4, 10]])

In [9]:
array_2d.ndim

2

In [10]:
array_2d.shape

(2, 4)

In [11]:
array_2d.nbytes

32

### Option 2: Creating array using NumPy functions

In [12]:
array_zeros = np.zeros((2,3), dtype='i')
array_zeros

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [13]:
array_ones = np.ones((2,2))
array_ones

array([[1., 1.],
       [1., 1.]])

In [14]:
array_sevens = np.full((2,3),7)
array_sevens

array([[7, 7, 7],
       [7, 7, 7]])

In [17]:
array_random = np.random.randint(10,90,(4,5))
print(array_random)

[[18 57 39 69 21]
 [86 39 14 18 42]
 [21 57 57 65 74]
 [26 88 61 76 43]]


### Accessing items from an array

In [18]:
array_random[1][2] # Using index

14

In [19]:
array_random[1, 2:4] # We can use slicing as well

array([14, 18])

In [20]:
print(array)

[2 5 7 9]


In [21]:
array[1::2] # slicing - array[start index: end index: step]

array([5, 9])

### Set/change value of an array item

In [22]:
array[1] = 10 # Use assignment operator for setting the value

print(array)

[ 2 10  7  9]


In [23]:
print(array_random)

[[18 57 39 69 21]
 [86 39 14 18 42]
 [21 57 57 65 74]
 [26 88 61 76 43]]


In [24]:
array_random[0][1] = 44

print(array_random)

[[18 44 39 69 21]
 [86 39 14 18 42]
 [21 57 57 65 74]
 [26 88 61 76 43]]


### Copy an array to other array

In [25]:
array_random_copy = array_random #Shallow copy

print(array_random_copy)

[[18 44 39 69 21]
 [86 39 14 18 42]
 [21 57 57 65 74]
 [26 88 61 76 43]]


In [26]:
array_random_copy[0][0] = 0 # Change in 'array_random_copy' will modify the 'array_random'

In [27]:
print(array_random)

[[ 0 44 39 69 21]
 [86 39 14 18 42]
 [21 57 57 65 74]
 [26 88 61 76 43]]


In [28]:
array_random_copy = array_random.copy() # Deep copy

In [29]:
array_random_copy[0][1] = 0 # Change in 'array_random_copy' will NOT modify the 'array_random'

In [30]:
print(array_random_copy)

[[ 0  0 39 69 21]
 [86 39 14 18 42]
 [21 57 57 65 74]
 [26 88 61 76 43]]


In [31]:
print(array_random)

[[ 0 44 39 69 21]
 [86 39 14 18 42]
 [21 57 57 65 74]
 [26 88 61 76 43]]
